/// /////////////////
// Wallpaper
/// /////////////////
/**
* Use the chrome.wallpaper API to change the ChromeOS wallpaper.
* Permissions:  "wallpaper"
* Important: This API works only on Chrome OS.
* @since Chrome 43.
*/

export interface WallpaperDetails {
  /** Optional. The jpeg or png encoded wallpaper image. */
  data?: ArrayBuffer | undefined
  /** Optional. The URL of the wallpaper to be set. */
  url?: string | undefined
  /**
       * The supported wallpaper layouts.
       * One of: "STRETCH", "CENTER", or "CENTER_CROPPED"
       */
  layout: 'STRETCH' | 'CENTER' | 'CENTER_CROPPED'
  /** The file name of the saved wallpaper. */
  filename: string
  /** Optional. True if a 128x60 thumbnail should be generated. */
  thumbnail?: boolean | undefined
}
export default interface _ {

  /**
   * Sets wallpaper to the image at url or wallpaperData with the specified layout
   * @param callback
   * Optional parameter thumbnail: The jpeg encoded wallpaper thumbnail. It is generated by resizing the wallpaper to 128x60.
   */
  setWallpaper: (details: WallpaperDetails, callback: (thumbnail?: ArrayBuffer) => void) => void
}
